RFCK/ViewModels/Products/ProductDetailsViewModel.cs
using RFCK.ViewModels.Ingredients;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RFCK.ViewModels.Products
{
    public class ProductDetailsViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int Weight { get; set; }
        public string Category { get; set; }
        public bool InStock { get; set; }
        public string ImageUrl { get; set; }
        public double Rating { get; set; }
        public int Votes { get; set; }
        public IEnumerable<IngredientViewModel> Ingredients { get; set; }
    }
}

RFCK/ViewModels/Products/ProductListViewModel.cs
namespace RFCK.ViewModels.Products
{
    public class ProductListViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int Weight { get; set; }
        public string Ingredients { get; set; }
        public string Category { get; set; }
        public bool InStock { get; set; }
        public string ImageUrl { get; set; }
    }
}

RFCK/Controllers/CategoriesController.cs
using MediatR;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RFCK.Common.Queries.Categories;
using System.Linq;
using RFCK.Util;
using RFCK.Filters;
using Microsoft.AspNetCore.Authorization;
using RFCK.Common;

namespace RFCK.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly IMediator _mediator;

        public CategoriesController(
            IMediator mediator)
        {
            _mediator = mediator;
        }

        [Route("~/Menu")]
        public async Task<IActionResult> Menu()
        {
            var response = await _mediator.Send(new GetCategoriesQuery());
            return View(response.Data.Select(Chizu.ToCategoryViewModel));
        }

        [Route("~/api/[controller]")]
        public async Task<IActionResult> Get()
        {
            var response = await _mediator.Send(new GetCategoriesQuery());
            return Ok(response.Data.Select(Chizu.ToCategoryViewModel));
        }

        [HttpPost]
        [ModelStateActionFilter]
        [Authorize(Roles = Roles.Admin)]
        [Route("~/api/[controller]")]
        public async Task<IActionResult> Create([FromForm] CreateCategoryCommand cmd)
        {
            var response = await _mediator.Send(cmd);

            if (!response.Succeded)
                return UnprocessableEntity(response.Error);

            return Ok(response.Data);
        }

        [HttpPut]
        [ModelStateActionFilter]
        [Authorize(Roles = Roles.Admin)]
        [Route("~/api/[controller]/{id}")]
        public async Task<IActionResult> Edit(int id, [FromForm] EditCategoryCommand cmd)
        {
            var response = await _mediator.Send(cmd);

            if (!response.Succeded)
                return UnprocessableEntity(response.Error);

            return Ok(Chizu.ToCategoryViewModel(response.Data));
        }

        [HttpDelete]
        [ModelStateActionFilter]
        [Authorize(Roles = Roles.Admin)]
        [Route("~/api/[controller]/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var response = await _mediator.Send(new DeleteCategoryCommand { Id = id });

            if (!response.Succeded)
                return UnprocessableEntity(response.Error);

            return Ok(id);
        }
    }
}

RFCK/Controllers/ProductsController.cs
using MediatR;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using RFCK.Common.Queries.Products;
using Microsoft.AspNetCore.Authorization;
using RFCK.Util;
using RFCK.Common;
using RFCK.Filters;
using RFCK.Extensions;

namespace RFCK.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IMediator _mediator;

        public ProductsController(
            IMediator mediator)
        {
            _mediator = mediator;
        }

        [HttpGet]
        [Authorize(Roles = Roles.Admin)]
        [Route("~/[controller]/Add")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = Roles.Admin)]
        [Route("~/[controller]/Add")]
        public async Task<IActionResult> Create([FromForm] CreateProductCommand cmd)
        {
            if (ModelState.IsValid)
            {
                var response = await _mediator.Send(cmd);

                if (!response.Succeded)
                {
                    ModelState.AddModelError("err", response.Error.Message);
                    return View();
                }

                return RedirectToAction("Products", "Dashboard");
            }

            return View();
        }

        [Route("~/Categories/{category}")]
        public async Task<IActionResult> GetByCategory(string category, int p = 1, SortType s = SortType.ByPopularity)
        {
            if (category == null)
                return NotFound();

            ViewData["Category"] = category.Capitalize();

            var response = await _mediator.Send(new GetProductsByCategoryPaginatedQuery { Category = category, PageNumber = p, SortType = s });

            if (!response.Succeded)
                return NotFound();
            
            ViewBag.TotalPages = response.Data.TotalPages;
            ViewBag.CurrentPage = response.Data.CurrentPage;
            ViewBag.PrevPage = response.Data.HasPrev ? HttpContext.Request.Path.Value + "?p=" + (response.Data.CurrentPage - 1) : null;
            ViewBag.NextPage = response.Data.HasNext ? HttpContext.Request.Path.Value + "?p=" + (response.Data.CurrentPage + 1) : null;

            return View(response.Data.Items.Select(Chizu.ToProductListViewModel));
        }

        [Route("~/[controller]/{id}")]
        public async Task<IActionResult> Details(int id)
        {
            var response = await _mediator.Send(new GetProductDetailsQuery { Id = id });

            if (!response.Succeded)
                return NotFound();

            ViewBag.UserRating = response.Data.Ratings.FirstOrDefault(r => r.UserId == User.GetUserId())?.Value ?? 0;

            return View(Chizu.ToProductDetailsViewModel(response.Data));
        }

        [HttpDelete]
        [ModelStateActionFilter]
        [Authorize(Roles = Roles.Admin)]
        [Route("~/api/[controller]/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var response = await _mediator.Send(new DeleteProductCommand { Id = id });
            return Ok(id);
        }

        [HttpPut]
        [ModelStateActionFilter]
        [Authorize(Roles = Roles.Admin)]
        [Route("~/api/[controller]/{id}")]
        public async Task<IActionResult> Edit(int id, [FromForm] EditProductCommand cmd)
        {
            var response = await _mediator.Send(cmd);

            if (!response.Succeded)
                return BadRequest(response.Error);

            return Ok(Chizu.ToProductListViewModel(response.Data));
        }

        [HttpPost]
        [Authorize]
        [ModelStateActionFilter]
        [Route("~/api/[controller]/rate")]
        public async Task<IActionResult> Rate([FromForm] int id, [FromForm] int rating)
        {
            var response = await _mediator.Send(new RateProductCommand
            {
                UserId = User.GetUserId(),
                ProductId = id,
                Rating = rating
            });

            if (!response.Succeded)
                return BadRequest(response.Error);

            return Ok(response.Data);
        }
    }
}

RFCK/ViewComponents/SuggestedViewComponent.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using RFCK.Common.Queries.Products;
using RFCK.Util;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace RFCK.ViewComponents
{
    public class SuggestedViewComponent : ViewComponent
    {
        private readonly IMediator _mediator;

        public SuggestedViewComponent(
            IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task<IViewComponentResult> InvokeAsync(string caption, string category, string exclude, string current)
        {
            ViewBag.Caption = caption;
            var response = string.IsNullOrEmpty(category)
                ? await _mediator.Send(new GetProductsQuery())
                : await _mediator.Send(new GetProductsByCategoryQuery { Category = category });
            var rnd = new Random();
            var vm = response.Data
                .Where(p => p.InStock && p.Category.Name != exclude && p.Name != current)
                .OrderBy(p => rnd.Next())
                .Take(4)
                .Select(Chizu.ToProductListViewModel);

            return View("../Shared/Components/Suggested.cshtml", vm);
        }
    }
}

RFCK/Views/Products/Create.cshtml
@using RFCK.Common.Queries.Products
@model CreateProductCommand
@{
    ViewData["Title"] = "Dashboard";
}

<span id="notification"></span>

<h2>Add Product</h2>
<div asp-validation-summary="All" class="text-danger"></div>
<div class="row">
    <div class="col-md-6">
        <form asp-controller="Dashboard" asp-action="AddProduct" method="post" enctype="multipart/form-data">

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input type="number" min="1" max="9999.99" asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Weight" class="control-label"></label>
                <input type="number" min="1" max="99999" asp-for="Weight" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ingredients" class="control-label">Ingredients</label>
                <div class="row">
                    <div class="col-11" style="padding-right: 5px">
                        <select id="ingredients" asp-for="Ingredients" title="Select ingredients..." class="selectpicker" data-live-search="true" data-selected-text-format="count" data-size="8" data-width="100%" multiple></select>
                    </div>
                    <div class="col-1" style="padding-left: 0">
                        <button type="button" class="btn btn-outline-dark" data-toggle="modal" data-target="#add-modal" data-name="Ingredient">+</button>
                    </div>
                </div>
                <span asp-validation-for="Ingredients" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label">Category</label>
                <div class="row">
                    <div class="col-11" style="padding-right: 5px">
                        <select id="categories" asp-for="Category" title="Select category..." class="selectpicker" data-live-search="true" data-size="8" data-width="100%"></select>
                    </div>
                    <div class="col-1" style="padding-left: 0">
                        <button type="button" class="btn btn-outline-dark" data-toggle="modal" data-target="#add-modal" data-name="Category">+</button>
                    </div>
                </div>
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group custom-file">
                <input id="image" type="file" asp-for="Image" class="custom-file-input" />
                <label asp-for="Image" class="custom-file-label">Choose image...</label>
                <span asp-validation-for="Image" class="text-danger"></span>
            </div> <br /> <br />
            <button type="submit" class="btn btn-primary">Add</button>
        </form>

        @* ---------- Modal ---------- *@
        <div class="modal fade" id="add-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel"></h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <span id="modal-notification"></span>
                        <form id="modal-form">
                            <div class="form-group">
                                <label for="modal-name" class="col-form-label"></label>
                                <input type="text" class="form-control" id="modal-name" required>
                            </div>
                            <div class="form-group custom-file">
                                <input id="modal-image" type="file" class="custom-file-input" required/>
                                <label for="modal-image" class="custom-file-label">Choose image...</label>
                            </div> <br /> <br />
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary">Add</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script>
        $(() => {
            getData('categories');
            getData('ingredients');
        });

        function addData(data, name) {
            if (!data.name || !data.image) {
                notifyModal('#modal-notification', 'danger', 'Please, enter all input fields.');
                return;
            }

            if (data.name.length < 2) {
                notifyModal('#modal-notification', 'danger', 'Please, enter a longer name.');
                return;
            }

            if (data.image.type.substring(0, 5) !== "image") {
                notifyModal('#modal-notification', 'danger', 'Invalid image format.');
                return;
            }

            let formData = new FormData();
            formData.append("name", data.name);
            formData.append("image", data.image);
            
            $.ajax({
                type: "POST",
                url: `${ROOT_URL}/api/${name}`,
                data: formData,
                processData: false,
                contentType: false,
                error: (err) => notifyModal('#modal-notification', 'danger', err.message),
                success: (res) => {
                    $(`#${name}`).append(`<option value="${res.id}">${res.name}</option>`);
                    $('.selectpicker').selectpicker('refresh');
                    notifyModal('#modal-notification', 'success', `<strong>${res.name}</strong> created successfully.`)
                    $('#add-modal').find('input:text').val('');
                    $('#add-modal').find('input:file').val('');
                    $('#add-modal').find('.custom-file-label').text('Choose image...');
                }
            });         
        }

        function getData(name) {
            $.get(`/api/${name}`, data => {
                data.forEach(c => $(`#${name}`).append(`<option value="${c.id}">${c.name}</option>`));
                $('.selectpicker').selectpicker('refresh');
            })
        }

        function notifyModal(container, type, message) {
            $(`${container}`).html(
                `<div class="alert alert-${type} alert-dismissible fade show" role="alert">
                    ${message}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>`
            );
        }

        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });

        $('#add-modal').on('show.bs.modal', function (event) {
            const button = $(event.relatedTarget);
            const recipient = button.data('name');
            const name = recipient === 'Category' ? 'categories' : 'ingredients';

            $(this).find('.modal-title').text('Add ' + recipient);
            $(this).find('.col-form-label').text(recipient + ' name:');
            console.log($(this).find('input:text').val());

            $(this).find('.btn-primary').on('click', () => addData({
                name: $(this).find('input:text').val(),
                image: $(this).find('input:file').prop('files')[0]
            }, name));
        });

        $('#add-modal').on('hide.bs.modal', function () {
            $(this).find('.btn-primary').off();
            $('#modal-notification').html('');
            $(this).find('input:text').val('');
            $(this).find('input:file').val('');
            $(this).find('.custom-file-label').text('Choose image...');
        });

    </script>
}

RFCK/Views/Products/Details.cshtml
@using RFCK.ViewModels.Products
@model ProductDetailsViewModel

@{
    ViewData["Title"] = Model.Name;
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
        <li class="breadcrumb-item"><a asp-controller="Categories" asp-action="Menu">Menu</a></li>
        <li class="breadcrumb-item active" aria-current="page"><a href="/Categories/@Model.Category">@Model.Category</a></li>
        <li class="breadcrumb-item active" aria-current="page">@Model.Name</li>
    </ol>
</nav>

<hr />

<div class="row">
    <div class="col-md-6">
        <img src="@Model.ImageUrl" class="img-fluid border rounded" alt="@Model.Name">
    </div>
    <div class="col-md-6">
        <h1 class="card-title">@Model.Name</h1>
        <h3 class="card-title">@Model.Price UAH - <span>@Model.Weight</span>g</h3>
        <span id="rating-block"><span class='starrr' data-rating="@ViewBag.UserRating" data-product="@Model.Id" data-enabled="@User.Identity.IsAuthenticated"></span></span> &nbsp;
        <span id="rating-caption"><small class="text-muted"><em>(@Model.Votes @if (Model.Votes == 1) {<span>vote</span>} else {<span>votes</span>}, rating @Model.Rating out of 5)</em></small></span>
        <hr />
        <h3></h3>

        @if (Model.Ingredients.Count() > 0)
        {
            <p class="card-text"><u><em>Ingredients:</em></u></p>
        }
        @foreach (var i in Model.Ingredients)
        {
            @*<img src="@i.ImageUrl" class="img-fluid" width="75" height="75" />*@
            <figure class="figure">
                <img src="@i.ImageUrl" class="figure-img img-fluid rounded" alt="@i.Name Pic" width="75" height="75">
                <figcaption class="figure-caption text-center">@i.Name</figcaption>
            </figure>
        }
        @if (Model.Ingredients.Count() > 0)
        {
            <hr />
        }
        <p></p>
        <button name="@Model.Id" class="btn btn-outline-dark btn-lg add-to-cart">Add to cart</button>
    </div>
</div>

<br /><br />
@await Component.InvokeAsync("Suggested", new { Caption = "Recommended", Exclude = "Drinks", Current = Model.Name })

@if (Model.Category != "Drinks")
{
    <br />
    @await Component.InvokeAsync("Suggested", new { Caption = "Get something to drink", Category = "Drinks" })
}

@section Scripts {
    <script src="~/js/starrr.js"></script>
    <script>
        $(document).ready(() => {
            $('.starrr').starrr({
                rating: parseInt($('.starrr').attr('data-rating')),
                readOnly: $('.starrr').attr('data-enabled') === "True" ? false : true
            });

            $('.starrr').on('starrr:change', function (e, value) {
                $.ajax({
                    type: 'POST',
                    url: `${ROOT_URL}/api/products/rate`,
                    data: { id: e.target.attributes["data-product"].value, rating: value },
                    error: err => console.log(err),
                    success: res => {
                        $("#rating-caption").html(`<small class="text-muted"><em>(${res.votes} ${res.votes === 1 ? "vote" : "votes"}, rating ${res.rating} out of 5)</em></small>`)
                    }
                });
            })

            if ($('.starrr').attr('data-enabled') === "False") {
                $('#rating-block').click(() => {
                    notify('info', 'Please authenticate before rating a food item.')
                });
            }
        })
    </script>
}

RFCK/Views/Products/GetByCategory.cshtml
@using RFCK.ViewModels.Products
@model IEnumerable<ProductListViewModel>

@{
    ViewData["Title"] = ViewData["Category"];
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
        <li class="breadcrumb-item"><a asp-controller="Categories" asp-action="Menu">Menu</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Category"]</li>
    </ol>
</nav>



@*<h1>@ViewData["Title"]</h1>*@
<hr />


@await Html.PartialAsync("_ProductList", Model)

@if (ViewBag.TotalPages > 1)
{
    <nav>
        <ul class="pagination justify-content-center">
            @if (ViewBag.PrevPage == null)
            {
                <li class="page-item disabled">
                    <span class="page-link">&laquo;</span>
                </li>
            }
            else
            {
                <li class="page-item">
                    <a class="page-link" href="@ViewBag.PrevPage" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            }

            @for (var i = 1; i <= ViewBag.TotalPages; i++)
            {
                if (ViewBag.CurrentPage == i)
                {
                    <li class="page-item active" aria-current="page">
                        <span class="page-link">@i</span>
                    </li>
                }
                else
                {
                    <li class="page-item">
                        <a class="page-link" href="@Context.Request.Path?p=@i">@i</a>
                    </li>
                }
            }

            @if (ViewBag.NextPage == null)
            {
                <li class="page-item disabled">
                    <span class="page-link">&raquo;</span>
                </li>
            }
            else
            {
                <li class="page-item">
                    <a class="page-link" href="@ViewBag.NextPage" aria-label="Previous">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            }
        </ul>
    </nav>
}