RFCK/ViewModels/Products/ProductListViewModel.cs
namespace RFCK.ViewModels.Products
{
    public class ProductListViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int Weight { get; set; }
        public string Ingredients { get; set; }
        public string Category { get; set; }
        public bool InStock { get; set; }
        public string ImageUrl { get; set; }
    }
}

RFCK/Controllers/CategoriesController.cs
using MediatR;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RFCK.Common.Queries.Categories;
using System.Linq;
using RFCK.Util;
using RFCK.Filters;
using Microsoft.AspNetCore.Authorization;
using RFCK.Common;

namespace RFCK.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly IMediator _mediator;

        public CategoriesController(
            IMediator mediator)
        {
            _mediator = mediator;
        }

        [Route("~/Menu")]
        public async Task<IActionResult> Menu()
        {
            var response = await _mediator.Send(new GetCategoriesQuery());
            return View(response.Data.Select(Chizu.ToCategoryViewModel));
        }

        [Route("~/api/[controller]")]
        public async Task<IActionResult> Get()
        {
            var response = await _mediator.Send(new GetCategoriesQuery());
            return Ok(response.Data.Select(Chizu.ToCategoryViewModel));
        }

        [HttpPost]
        [ModelStateActionFilter]
        [Authorize(Roles = Roles.Admin)]
        [Route("~/api/[controller]")]
        public async Task<IActionResult> Create([FromForm] CreateCategoryCommand cmd)
        {
            var response = await _mediator.Send(cmd);

            if (!response.Succeded)
                return UnprocessableEntity(response.Error);

            return Ok(response.Data);
        }

        [HttpPut]
        [ModelStateActionFilter]
        [Authorize(Roles = Roles.Admin)]
        [Route("~/api/[controller]/{id}")]
        public async Task<IActionResult> Edit(int id, [FromForm] EditCategoryCommand cmd)
        {
            var response = await _mediator.Send(cmd);

            if (!response.Succeded)
                return UnprocessableEntity(response.Error);

            return Ok(Chizu.ToCategoryViewModel(response.Data));
        }

        [HttpDelete]
        [ModelStateActionFilter]
        [Authorize(Roles = Roles.Admin)]
        [Route("~/api/[controller]/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var response = await _mediator.Send(new DeleteCategoryCommand { Id = id });

            if (!response.Succeded)
                return UnprocessableEntity(response.Error);

            return Ok(id);
        }
    }
}

RFCK/Controllers/DashboardController.cs
using MediatR;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RFCK.Common.Queries.Products;
using RFCK.Util;
using RFCK.Common.Queries.Categories;
using RFCK.Common.Queries.Ingredients;

namespace RFCK.Controllers
{
    public class DashboardController : Controller
    {
        private readonly IMediator _mediator;

        public DashboardController(
            IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task<IActionResult> Products()
        {
            var response = await _mediator.Send(new GetProductsQuery());
            return View(response.Data.Select(Chizu.ToProductListViewModel));
        }

        public async Task<IActionResult> Categories()
        {
            var response = await _mediator.Send(new GetCategoriesQuery());
            return View(response.Data.Select(Chizu.ToCategoryViewModel));
        }

        public async Task<IActionResult> Ingredients()
        {
            var response = await _mediator.Send(new GetIngredientsQuery());
            return View(response.Data.Select(Chizu.ToIngredientViewModel));
        }
    }
}

RFCK/Controllers/OrderController.cs
using MediatR;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RFCK.Common;
using RFCK.Common.Data.Entities;
using RFCK.Extensions;
using RFCK.ViewModels.ShoppingCart;
using RFCK.Common.Queries.Orders;
using System.Linq;
using RFCK.Util;
using RFCK.ViewModels.Orders;

namespace RFCK.Controllers
{
    public class OrderController : Controller
    {
        private readonly IMediator _mediator;
        private readonly UserManager<User> _userManager;

        public OrderController(
            UserManager<User> userManager,
            IMediator mediator)
        {
            _userManager = userManager;
            _mediator = mediator;
        }

        public async Task<IActionResult> Checkout()
        {
            var cart = HttpContext.Session.Get<ShoppingCart>(SessionKeys.Cart);

            if (cart == null)
                return RedirectToAction("Index", "Home");

            var response = await _mediator.Send(new GetOrderInfoQuery
            {
                UserId = User.GetUserId(),
                CartItems = cart.Items.Values.Select(Chizu.ToCartItemDto)
            });

            var result = Chizu.ToOrderCheckoutViewModel(response.Data);

            return View(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Checkout(OrderCheckoutViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var cart = HttpContext.Session.Get<ShoppingCart>(SessionKeys.Cart);

            if (cart == null)
                return RedirectToAction("Index", "Home");

            var response = await _mediator.Send(new GetOrderInfoQuery
            {
                UserId = User.GetUserId(),
                CartItems = cart.Items.Values.Select(Chizu.ToCartItemDto)
            });

            var result = Chizu.ToOrderCheckoutViewModel(response.Data);

            return View(result);
        }
    }
}

RFCK/Views/Shared/_Layout.cshtml
@using RFCK.Common
@using RFCK.Extensions

@{
    var count = Context.Session.Get<int?>(SessionKeys.CartItemCount);
    ViewBag.CartItemsCount = count == 0 ? null : count;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    @*<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/simplex/bootstrap.min.css" />*@
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/css/bootstrap-select.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
</head>
<body>

    <!-- #wrapper -->
    <div class="d-flex" id="wrapper">
        <!-- Sidebar -->
        <div class="bg-light border-right" id="sidebar-wrapper">
            <a asp-controller="Home" asp-action="Index" class="nav-link" style="padding: 0; color: black">
                <img src="~/img/logo/logo-white.png" height="96" width="96" alt="Logo" />
            </a>
            <div class="list-group list-group-flush">
                <a href="/Categories/Pizza" class="list-group-item list-group-item-action sidebar-link bg-light">
                    <i class="fas fa-pizza-slice cat"></i>
                    <div>Pizza</div>
                </a>
                <a href="/Categories/Sushi" class="list-group-item list-group-item-action sidebar-link bg-light">
                    <i class="fas fa-fish cat"></i>
                    <div>Sushi</div>
                </a>
                <a href="/Categories/Burgers" class="list-group-item list-group-item-action sidebar-link bg-light">
                    <i class="fas fa-hamburger cat"></i>
                    <div>Burgers</div>
                </a>
                <a href="/Categories/Drinks" class="list-group-item list-group-item-action sidebar-link bg-light">
                    <i class="fas fa-cocktail cat"></i>
                    <div>Drinks</div>
                </a>
            </div>
        </div>
        <!-- /#sidebar-wrapper -->
        <div id="page-content-wrapper">

            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">

                <!-- Button trigger modal -->
                <button class="btn navbar-brand" data-toggle="modal" data-target="#cart-modal" style="padding: 0">
                    <i class="fas fa-shopping-cart"></i> Cart
                    <span class="badge badge-primary badge-cart">@ViewBag.CartItemsCount</span>
                </button>

                <button class="btn" id="menu-toggle" style="display: none"></button>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <form class="form-inline mt-2 mt-md-0">
                        <div class="input-group">
                            <input class="form-control typeahead" type="text" placeholder="Search" aria-label="Search">
                            <div class="input-group-append">
                                <button class="btn btn-outline-success" type="submit"><i class="fas fa-search"></i></button>
                            </div>
                        </div>
                    </form>

                    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">

                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Categories" asp-action="Menu">Menu</a>
                        </li>

                        @if (User.IsInRole(Roles.Admin))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Dashboard" asp-action="Products">Dashboard</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Products" asp-action="Create">Add</a>
                            </li>
                        }

                        <partial name="_LoginPartial" />

                    </ul>
                </div>
            </nav>
            <!-- /Navbar -->

            <!-- Page Content -->
            <div id="blyado-wrapper" class="container" style="margin-top: 15px;">
                @RenderBody()
            </div>
            <!-- /Page Content -->

            <!-- Footer -->
            <footer class="mt-5 pt-5 pb-5 footer border-top">
                <div class="ml-5 mr-5">
                    <div class="">
                        <div class="row">
                            <div class="col-lg-5 col-xs-12 about-company">
                                <h2>RFCK</h2>
                                <p class="pr-5 text-black-50">
                                    Death Stranding will bomb. Kojima is a hack. Go play Uchikoshi's new game.
                                </p>
                                <p><a href="#"><i class="fab fa-facebook-square mr-2"></i></a><a href="#"><i class="fab fa-instagram mr-2"></i></a><a href="#"><i class="fab fa-twitter-square"></i></a></p>
                            </div>
                            <div class="col-lg-3 col-xs-12 links">
                                <h4 class="mt-lg-0 mt-sm-3">Menu</h4>
                                <ul class="m-0 p-0">
                                    <li>- <a href="/categories/pizza">Pizza</a></li>
                                    <li>- <a href="/categories/sushi">Sushi</a></li>
                                    <li>- <a href="/categories/burgers">Burgers</a></li>
                                    <li>- <a href="/categories/drinks">Drinks</a></li>
                                </ul>
                            </div>
                            <div class="col-lg-4 col-xs-12 location">
                                <h4 class="mt-lg-0 mt-sm-4">Location</h4>
                                <p class="text-black-50">22, I'm fucking dying here. Help, let me out.</p>
                                <p class="mb-0"><i class="fas fa-phone mr-3"></i>(299) 792-458</p>

                                <p><i class="fas fa-envelope mr-3"></i>info@rfck.com</p>
                            </div>
                        </div>
                    </div>
                    <div class="row mt-5">
                        <div class="col copyright">
                            <hr />
                            <p class=""><small class="text-black-50">© 2019. All Rights Reserved.</small></p>
                        </div>
                    </div>
                </div>
            </footer>
            <!-- /.footer -->

        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->
    <!-- Shopping Cart Modal -->
    <div class="modal fade" id="cart-modal" tabindex="-1" role="dialog" aria-labelledby="cart-modal-label" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="cart-modal-label">Shopping cart</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div id="cart-loader" style="display: block">
                        <div class="d-flex justify-content-center">
                            <div class="spinner-border" style="width: 3rem; height: 3rem;" role="status">
                                <span class="sr-only">Loading...</span>
                            </div>
                        </div>
                    </div>
                    <!-- Body -->
                    <div id="cart-modal-body">

                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <span id="checkout-btn"><a asp-controller="Order" asp-action="Checkout" class="btn btn-primary" role="button">Checkout</a></span>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/bootstrap-select.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mouse0270-bootstrap-notify/3.1.7/bootstrap-notify.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

RFCK/Views/Shared/_ProductList.cshtml
@using RFCK.ViewModels.Products
@model IEnumerable<ProductListViewModel>

<div class="card-deck">
    @foreach (var p in Model)
    {
        if (p.InStock)
        {
            <div class="col-lg-3 col-md-4 col-sm-6" style="margin-bottom: 25px">
                <div class="card p-card shadow-sm rounded border-0">
                    <a href="/Products/@p.Id">
                        <img class="card-img-top" src="@p.ImageUrl" alt="@p.Name">
                    </a>
                    <div class="card-body">
                        <a href="/Products/@p.Id" style="color: inherit; text-decoration: none">
                            <h5 class="card-title">@p.Name</h5>
                            <h6 class="card-title">@p.Price UAH</h6>
                            <p class="card-text"><small><em>@p.Ingredients</em></small></p>
                        </a>
                        <button name="@p.Id" type="button" class="btn btn-outline-dark add-to-cart" style="margin-top: 0.75rem; display:block">Add to cart</button>
                    </div>
                </div>
            </div>
        }
    }
</div>